stages: ["test", "generate", "build"]

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        EB_PATH: "/data/rosi/shared/eb/easybuild"
        CUSTOM_CI_BUILDS_DIR: "/bigdata/rz/rosi_easybuild"
    # Please add paths where you want to store the generated modules and git clone respectively.
    - when: always
      variables: 
        EB_PATH: ""
        CUSTOM_CI_BUILDS_DIR: ""

variables:

# Set the architecture and partition for the builds.
# Set slurm parameters, take enough memory for the builds, otherwise they will fail.
  ARCH: 'volta'
  PARTITION: 'gpu-v100'
  NTASKS_PER_NODE: '8'
  MEM: '100G'

# Set the CUDA compute capabilities for the builds. 
# This should be set according to the GPU architecture you are targeting. 
# For volta it is 7.0, for ampere it is 8.0, for hopper it is 9.0, for blackwell it is 10.0
 # CUDA_COMPUTE_CAPABILITIES: "9.0"

# Do NOT change the below variables
  EB_SOURCE: "/bigdata/rz/sudhar46/easybuild_manual_test/codebase/eb_env"
  SOURCE_PATH: "/data/rosi/shared/eb/easybuild_source"

default:
  tags: ['rosi-slurm']
  before_script:
    - ml python/3.14
    - ml hopper
    - source $EB_SOURCE/bin/activate
  id_tokens:
    CI_JOB_JWT:
      aud: "https://codebase.helmholtz.cloud"

test_gitlab_ci_hook:
  stage: test
  before_script: []
  script:
    - ml python/3.14
    - python3 --version
    - python3 -m unittest discover -s tests -p "test_*.py" -v
  rules:
    - changes:
        - gitlab_ci_hook.py
        - tests/test_gitlab_ci_hook.py

generate_pipeline:
  stage: generate
  script:
    - echo "Generating EasyBuild GitLab CI pipeline for foss and CUDA toolchains"
    - echo "DEBUG Environment variables:"
    - echo "GITLAB_CI_GENERATE=$GITLAB_CI_GENERATE"
    - echo "Current directory is $(pwd)"
    - ls -la gitlab_ci_hook.py || echo "Hook file NOT FOUND"
    - |
      eb --hooks=gitlab_ci_hook.py \
         --installpath=${EB_PATH}/${ARCH} \
         --installpath-modules=${EB_PATH}/${ARCH}/modules \
         --tmp-logdir=eblog --buildpath=ebbuild \
         --sourcepath=/data/rosi/shared/eb/easybuild_source \
         --robot --robot-paths=${CI_PROJECT_DIR}/custom_easyconfigs: \
         --module-naming-scheme=CategorizedHMNS \
         --insecure-download --disable-mpi-tests --skip-test-step --skip-test-cases \
         --accept-eula-for=Intel-oneAPI,CUDA,NVHPC,cuDNN \
         --trace --max-parallel=${NTASKS_PER_NODE} \
         --cuda-compute-capabilities=7.0 \
         OpenMPI-5.0.3-nvidia-compilers-25.3-CUDA-12.8.0.eb

    - echo "Pipeline generation completed"
    - cat easybuild-child-pipeline.yml

  artifacts:
    paths:
      -  easybuild-child-pipeline.yml
    expire_in: 1 week

execute_builds:
  stage: build
  when: always
  trigger:
    include:
      - artifact:  ${CI_PROJECT_DIR}/easybuild-child-pipeline.yml
        job: generate_pipeline
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    SCHEDULER_PARAMETERS: "--nodes=1 --ntasks-per-node=${NTASKS_PER_NODE} --partition=${PARTITION} --mem=${MEM}"
