stages: ["test", "generate", "build"]

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        EB_PATH: "/bigdata/rz/rosi_easybuild"
        CUSTOM_CI_BUILDS_DIR: "/bigdata/rz/rosi_easybuild"
    # Please add paths where you want to store the generated modules and git clone respectively.
    - when: always
      variables: 
        EB_PATH: "/bigdata/nanostructures/DFT/DI/clusterebtemp"
        CUSTOM_CI_BUILDS_DIR: "/bigdata/nanostructures/DFT/DI/clusterebtemp/build"

variables:
  ARCH: 'hopper'
  PARTITION: 'gpu-h100'

#Do not change the below variables
  EB_SOURCE: "/bigdata/rz/sudhar46/easybuild_manual_test/codebase/eb_env"
  SOURCE_PATH: "/data/rosi/shared/eb/easybuild_source"


default:
  tags: ['rosi-slurm']
  before_script:
    - ml python
    - source $EB_SOURCE/bin/activate
  id_tokens:
    CI_JOB_JWT:
      aud: "https://codebase.helmholtz.cloud"

test_gitlab_ci_hook:
  stage: test
  before_script: []
  script:
    - python3 --version
    - python3 -m unittest discover -s tests -p "test_*.py" -v
  rules:
    - changes:
        - gitlab_ci_hook.py
        - tests/test_gitlab_ci_hook.py

generate_pipeline:
  stage: generate
  script:
    - echo "Generating EasyBuild GitLab CI pipeline for foss and CUDA toolchains"
    - echo "DEBUG Environment variables:"
    - echo "GITLAB_CI_GENERATE=$GITLAB_CI_GENERATE"
    - echo "Current directory is $(pwd)"
    - ls -la gitlab_ci_hook.py || echo "Hook file NOT FOUND"
    - |
      eb --hooks=gitlab_ci_hook.py \
         --installpath=${EB_PATH}/${ARCH} \
         --installpath-modules=${EB_PATH}/${ARCH}/modules \
         --tmp-logdir=eblog --buildpath=ebbuild \
         --sourcepath=/data/rosi/shared/eb/easybuild_source \
         --robot --insecure-download --disable-mpi-tests --skip-test-step --skip-test-cases \
         --robot-paths=${CI_PROJECT_DIR}/easyconfigs \
         --module-naming-scheme=CategorizedHMNS \
         --accept-eula-for=Intel-oneAPI,CUDA,NVHPC,cuDNN \
         --trace --max-parallel=8 --cuda-compute-capabilities=9.0 \
         CUDA-12.1.1.eb \
         CUDA-12.2.2.eb \
         CUDA-12.3.2.eb \
         CUDA-12.4.0.eb \
         CUDA-12.5.0.eb \
         CUDA-12.6.0.eb \
         CUDA-12.8.0.eb \
         CUDA-12.9.1.eb \
         CUDA-13.0.2.eb \
         CUDA-13.1.0.eb

    - echo "Pipeline generation completed"
    - cat easybuild-child-pipeline.yml

  artifacts:
    paths:
      -  easybuild-child-pipeline.yml
    expire_in: 1 week

execute_builds:
  stage: build
  when: always
  trigger:
    include:
      - artifact:  ${CI_PROJECT_DIR}/easybuild-child-pipeline.yml
        job: generate_pipeline
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    SCHEDULER_PARAMETERS: "--nodes=1 --ntasks-per-node=8 --partition=${PARTITION} --mem=500G -A rz --qos=qos_rz"
